name: install-nccl
inputs:
  platform:
    required: false
runs:
  using: composite
  steps:
  - name: Install NCCL 2.7.8 for CUDA 11.1
    run: |-
      cd /tmp
      export NCCL2_DEB=libnccl2_2.7.8-1+cuda11.1_amd64.deb
      export LIBNCCL_DEV_DEB=libnccl-dev_2.7.8-1+cuda11.1_amd64.deb
      wget --quiet https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64/$NCCL2_DEB
      wget --quiet https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64/$LIBNCCL_DEV_DEB
      sudo dpkg -i $NCCL2_DEB $LIBNCCL_DEV_DEB
    if: "'linux' == ${{ inputs.platform }}"
    shell: bash