name: install-cuda
inputs:
  platform:
    required: false
runs:
  using: composite
  steps:
  - name: Install wget from choco
    run: choco install --no-progress wget -y
    if: "'windows' == ${{ inputs.platform }}"
    shell: bash
  - name: Install CUDA 11.5
    run: |-
      cd $HOME
      # See  https://docs.nvidia.com/cuda/pdf/CUDA_Installation_Guide_Windows.pdf
      export CUDA_INSTALLER_NAME="cuda_11.5.2_496.13_windows.exe"
      wget --quiet https://developer.download.nvidia.com/compute/cuda/11.5.2/local_installers/$CUDA_INSTALLER_NAME
      # List of CUDA install options is https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html
      ./$CUDA_INSTALLER_NAME -s nvcc_11.5 cudart_11.5 cublas_dev_11.5 curand_dev_11.5 visual_studio_integration_11.5
      rm $CUDA_INSTALLER_NAME
    shell: bash.exe
    if: "'windows' == ${{ inputs.platform }}"