name: install-arrayfire
inputs:
  platform:
    required: false
runs:
  using: composite
  steps:
  - name: Install ArrayFire 3.8.1 with CUDA 11.4
    run: |-
      sudo apt update
      sudo apt install -y gnupg2 ca-certificates apt-utils software-properties-common
      sudo apt update
      sudo apt-key adv --fetch-key https://repo.arrayfire.com/GPG-PUB-KEY-ARRAYFIRE-2020.PUB
      echo "deb [arch=amd64] https://repo.arrayfire.com/debian all main" | sudo tee /etc/apt/sources.list.d/arrayfire.list
      sudo apt update
      sudo apt install arrayfire-cmake=3.8.1-2 arrayfire-headers=3.8.1-2
      sudo apt install arrayfire-cuda3-cuda-11-4=3.8.1-2 arrayfire-cuda3-dev=3.8.1-2
    if: "'linux' == ${{ inputs.platform }}"
    shell: bash
  - name: Install 7zip and axel from choco
    run: choco install --no-progress 7zip axel -y
    if: "'windows' == ${{ inputs.platform }}"
    shell: bash
  - name: Download and Install ArrayFire 3.8.1
    run: |-
      cd $HOME
      export AF_INSTALLER_NAME="ArrayFire-v3.8.1-CUDA-11.4.exe"
      axel --quiet -n 16 https://arrayfire.s3.amazonaws.com/3.8.1/$AF_INSTALLER_NAME
      7z.exe x $AF_INSTALLER_NAME -o"C:\Program Files\ArrayFire" -y
      rm $AF_INSTALLER_NAME
    shell: bash.exe
    if: "'windows' == ${{ inputs.platform }}"
  - name: Install ArrayFire from Homebrew
    run: brew install arrayfire
    if: "'macos-arm' == ${{ inputs.platform }}"
    shell: bash