name: install-build-dependencies
inputs:
  platform:
    required: false
runs:
  using: composite
  steps:
  - name: Install CMake from Homebrew
    run: brew install cmake
    if: "'macos-arm' == ${{ inputs.platform }}"
    shell: bash
  - name: Add MSVC CMake binary to PATH
    run: echo 'export PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\:${PATH}"' >> $BASH_ENV
    if: "'windows' == ${{ inputs.platform }}"
    shell: bash
  - name: Remove old Windows SDK headers
    run: |-
      export WINDOWS_SDK_HEADER_PATH="C:\Program Files (x86)\Windows Kits\10\Include"
      ls "${WINDOWS_SDK_HEADER_PATH}" | head -n -1 | xargs -I{} rm -rf "${WINDOWS_SDK_HEADER_PATH}/{}"
    if: "'windows' == ${{ inputs.platform }}"
    shell: bash